
IMPULSE_MULTIPLIER = 2.5
IMPULSE_MINIMUM_SAMPLE = 5
IMPULSE_ABSOLUTE_FLOOR = 500.0  # used below IMPULSE_MINIMUM_SAMPLE, before the mean is trusted
UNUSUAL_CATEGORY_ID = 199

THRESHOLD_LEVELS: list[int] = [50, 75, 90, 95]
PROJECTION_TRAILING_WINDOWS_DAYS: list[int] = [7, 14]
